In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the data from the data folder
data_path = 'data/ratings.csv'  # Replace 'your_file_name.csv' with the actual file name
data = pd.read_csv(data_path)

# Display the first few rows of the data
print(data.head())

data.describe()

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858

KeyboardInterrupt:

In [4]:
# Load the data from the data folder
data_path = 'data/tags.csv'  # Replace 'your_file_name.csv' with the actual file name
data = pd.read_csv(data_path)

# Display the first few rows of the data
print(data.head())

data.describe()

   userId  movieId          tag   timestamp
0      22    26479  Kevin Kline  1583038886
1      22    79592     misogyny  1581476297
2      22   247150   acrophobia  1622483469
3      34     2174        music  1249808064
4      34     2174        weird  1249808102

             userId       movieId     timestamp
count  2.000072e+06  2.000072e+06  2.000072e+06
mean   8.192859e+04  7.189326e+04  1.528914e+09
std    3.810650e+04  7.480379e+04  1.290835e+08
min    2.200000e+01  1.000000e+00  1.135429e+09
25%    6.841300e+04  4.011000e+03  1.473615e+09
50%    7.821300e+04  5.232800e+04  1.574071e+09
75%    1.036980e+05  1.222940e+05  1.614740e+09
max    1.622790e+05  2.926290e+05  1.697155e+09

In [6]:
# Load the data from the data folder
data_path = 'data/movies.csv'  # Replace 'your_file_name.csv' with the actual file name
data = pd.read_csv(data_path)

# Display the first few rows of the data
print(data.head())

data.describe()

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

             movieId
count   87585.000000
mean   157651.365519
std     79013.402099
min         1.000000
25%    112657.000000
50%    165741.000000
75%    213203.000000
max    292757.000000

In [ ]:
# convert the timestamp to a datetime object
data['timestamp'] = pd.to_datetime(data['timestamp'], unit='s')

AttributeError: 'DataFrame' object has no attribute 'grouby'

In [ ]:
# average rating and count of ratings per user
user_ratings = data.groupby(['userId']).agg({'rating': ['count', 'mean']}).reset_index()

        userId rating
                count      mean
0            1    141  3.531915
1            2     52  4.269231
2            3    147  3.588435
3            4     27  2.629630
4            5     33  3.272727
...        ...    ...       ...
200943  200944    298  3.947987
200944  200945    108  3.101852
200945  200946     23  4.391304
200946  200947     61  3.950820
200947  200948    236  3.595339

[200948 rows x 3 columns]

In [9]:
# average rating per movie
movie_ratings = data.groupby(['movieId']).agg({'rating': ['count', 'mean']}).reset_index()
movie_ratings

      movieId rating
               count      mean
0           1  68997  3.897438
1           2  28904  3.275758
2           3  13134  3.139447
3           4   2806  2.845331
4           5  13154  3.059602
...       ...    ...       ...
84427  292731      1  4.000000
84428  292737      1  1.500000
84429  292753      1  4.000000
84430  292755      1  1.000000
84431  292757      1  3.500000

[84432 rows x 3 columns]